<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title> error on Memo Tut</title>
    <link>https://memotut.com/tags/error/</link>
    <description>Recent content in  error on Memo Tut</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Tue, 04 Feb 2020 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://memotut.com/tags/error/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>[Python] Response when ModuleNotFoundError: No module named&#39;XXX&#39; occurs in Python</title>
      <link>https://memotut.com/df4338913/</link>
      <pubDate>Tue, 04 Feb 2020 00:00:00 +0000</pubDate>
      
      <guid>https://memotut.com/df4338913/</guid>
      <description>This is a memo for dealing with the title.  This time, we assume there is no WTForms.
First, check if the module exists with pip show pip show WTForms Name: WTForms Version: 2.2.1 Summary: A flexible forms validation and rendering library for Python web development. Home-page: https://wtforms.readthedocs.io/ Author: Thomas Johansson, James Crasta Author-email: wtforms@simplecodes.com License: BSD Location: /Users/XXX/.pyenv/versions/3.7.5/lib/python3.7/site-packages Requires: Required-by: wtforms-validators, Flask-WTF  If it does not exist here, install the module (pip install Flask-WTF).</description>
    </item>
    
    <item>
      <title>[Python] Strange Python error message â€” was the code really executed?</title>
      <link>https://memotut.com/fed244b04/</link>
      <pubDate>Mon, 19 Jun 2017 00:00:00 +0000</pubDate>
      
      <guid>https://memotut.com/fed244b04/</guid>
      <description>## Strange error message, what&#39;s going on?  In a directory on a machine, I typed eval(&amp;quot;1/0&amp;quot;) into Python (CPython) in interactive mode.
Python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] on linux Type &amp;#34;help&amp;#34;, &amp;#34;copyright&amp;#34;, &amp;#34;credits&amp;#34; or &amp;#34;license&amp;#34; for more information. &amp;gt;&amp;gt;&amp;gt; eval(&amp;#34;1/0&amp;#34;) Traceback (most recent call last): File &amp;#34;&amp;lt;stdin&amp;gt;&amp;#34;, line 1, in &amp;lt;module&amp;gt; Should I go to bed soon? File &amp;#34;&amp;lt;string&amp;gt;&amp;#34;, line 1, in &amp;lt;module&amp;gt; It&amp;#39;s already the limit ZeroDivisionError: division by zero I see, a divide by zero runtime error, which is as expected.</description>
    </item>
    
  </channel>
</rss>