<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>CUDA on Memo Tut</title>
    <link>https://memotut.com/tags/cuda/</link>
    <description>Recent content in CUDA on Memo Tut</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Tue, 03 Dec 2019 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://memotut.com/tags/cuda/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>[Python] Problem that torch.cuda.is_available() of pytorch gives false</title>
      <link>https://memotut.com/problem-that-torch.cuda.is_available-of-pytorch-gives-false-7962d/</link>
      <pubDate>Tue, 03 Dec 2019 00:00:00 +0000</pubDate>
      
      <guid>https://memotut.com/problem-that-torch.cuda.is_available-of-pytorch-gives-false-7962d/</guid>
      <description>#Environment  ・Ubuntu 16.04 ・Python 3.7.3 ・Pytorch 1.2.0
GPU cannot be used with #pytorch
I thought about deeplearning, but it&amp;rsquo;s slow so check if you can see cuda in ipython.
In [1]: import torch In [2]: torch.cuda.is_available() Out[2]: False why? As a possible cause, I thought that NVIDIA-driver is not working,
(base) user@user:~$ nvidia-smi Tue Dec 3 11:29:10 2019 +------------------------------------------------- ----------------------------+ | NVIDIA-SMI 390.116 Driver Version: 390.116 | |-------------------------------+----------------- -----+----------------------+ | GPU Name Persistence-M| Bus-Id Disp.</description>
    </item>
    
  </channel>
</rss>