<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title> partially applicable on Memo Tut</title>
    <link>https://memotut.com/tags/partially-applicable/</link>
    <description>Recent content in  partially applicable on Memo Tut</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Sat, 14 Mar 2020 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://memotut.com/tags/partially-applicable/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>[Python] Points that are easy to make mistakes when using lambda in Python loop processing</title>
      <link>https://memotut.com/b25468068/</link>
      <pubDate>Sat, 14 Mar 2020 00:00:00 +0000</pubDate>
      
      <guid>https://memotut.com/b25468068/</guid>
      <description>I wrote the following code to &amp;quot;download 500 files in parallel&amp;quot; in Python.  from time import sleep from concurrent.futures import ThreadPoolExecutor def func(i): # Actually file download process sleep(1) print(f&amp;#34;{i}\n&amp;#34;, flush=True, end=&amp;#34;&amp;#34;) with ThreadPoolExecutor(max_workers=3) as executor: for i in range(500): Download files #0-499 in parallel executor.submit( lambda: func(i) ) When I execute this, I got the behavior like &amp;ldquo;Process is executed many times with the same number&amp;rdquo; as follows.</description>
    </item>
    
  </channel>
</rss>