<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <meta name="generator" content="Hugo 0.72.0" />

  
  <meta name="description" content="Some description">
  

  
  <link rel="apple-touch-icon" sizes="180x180" href="https://memotut.com/apple-touch-icon.png">

  
  <link rel="icon" type="image/png" sizes="32x32" href="https://memotut.com/favicon-32x32.png">

  
  <link rel="icon" type="image/png" sizes="16x16" href="https://memotut.com/favicon-16x16.png">

  
  <link rel="manifest" href="https://memotut.com/site.webmanifest">

  
  <link rel="mask-icon" href="https://memotut.com/safari-pinned-tab.svg" color="#5bbad5">

  <meta name="msapplication-TileColor" content="#da532c">

  <meta name="theme-color" content="#ffffff">

  
  <link rel="stylesheet" href="https://memotut.com/css/bootstrap.min.css" />

  
  <title>[Python] Strange Python error message — was the code really executed? | Memo Tut</title>
  

  <style>
body {
  min-width: 300px;
}

.custom-navbar {
  margin-bottom: 1em;
  height: 60px;
}

.custom-navbar a {
  display: inline-block; 
  padding: 18px 0;
  margin-right: 1em; 
  font-weight: bold; 
}

.custom-navbar a:hover,
.custom-navbar a:focus {
  text-decoration: none; 
}

@media print {
  .custom-navbar {
    display: none;
  }
}

article {
  padding-bottom: 1em;
}

img {
  max-width: 100%;
}


body {
  background-color: #fff;
}



body {
  color: #212529;
}



a {
  color: #007bff;
}



a:hover,
a:focus {
  color: #0056b3;
}



.custom-navbar {
  background-color: #212529;
}



.custom-navbar a {
  color: rgba(255, 255, 255, 0.75);
}



.custom-navbar a:hover,
.custom-navbar a:focus {
  color: rgba(255, 255, 255, 1);
}



.container {
  max-width: 800px;
}



pre {
  display: block;
  padding: 9.5px;
  word-break: break-all;
  word-wrap: break-word;
  background-color: #f5f5f5;
  border: 1px solid #ccc;
  border-radius: 4px;
}

pre code {
  padding: 0;
  font-size: inherit;
  color: inherit; 
  white-space: pre-wrap;
  background-color: transparent;
  border: none;
  border-radius: 0;
}

code {
  padding: 2px 4px;
  color: inherit; 
  background-color: #f5f5f5;
  border: 1px solid #ccc;
  border-radius: 4px;
  font-size: .9em;
}



blockquote,
.blockquote {
  padding: 10px 20px;
  margin: 0 0 20px;
  font-size: 1em;
  border-left: 5px solid #6c757d;
}

</style>
</head>

<body>
  <nav class="custom-navbar">
  <div class="container">
    
    <a href="/">Posts</a>
    
    <a href="/tags/">Tags</a>
    
    <a href="/about/">About</a>
    
    <a href="/index.xml">RSS</a>
    
  </div>
</nav>
  
  <div class="container">
    <article>
      <h1>[Python] Strange Python error message — was the code really executed?</h1>
<p>
  <small class="text-secondary">
  
  
  Jun 19, 2017
  </small>
  

<small><code><a href="https://memotut.com/tags/python">Python</a></code></small>


<small><code><a href="https://memotut.com/tags/error">error</a></code></small>

</p>
<pre><code>## Strange error message, what's going on?
</code></pre>
<p>In a directory on a machine, I typed <code>eval(&quot;1/0&quot;)</code> into Python (CPython) in interactive mode.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">Python <span style="color:#ae81ff">3.5</span><span style="color:#f92672">.</span><span style="color:#ae81ff">3</span> (default, Jan <span style="color:#ae81ff">19</span> <span style="color:#ae81ff">2017</span>, <span style="color:#ae81ff">14</span>:<span style="color:#ae81ff">11</span>:<span style="color:#ae81ff">04</span>)
[GCC <span style="color:#ae81ff">6.3</span><span style="color:#f92672">.</span><span style="color:#ae81ff">0</span> <span style="color:#ae81ff">20170118</span>] on linux
Type <span style="color:#e6db74">&#34;help&#34;</span>, <span style="color:#e6db74">&#34;copyright&#34;</span>, <span style="color:#e6db74">&#34;credits&#34;</span> <span style="color:#f92672">or</span> <span style="color:#e6db74">&#34;license&#34;</span> <span style="color:#66d9ef">for</span> more information<span style="color:#f92672">.</span>
<span style="color:#f92672">&gt;&gt;&gt;</span> eval(<span style="color:#e6db74">&#34;1/0&#34;</span>)
Traceback (most recent call last):
  File <span style="color:#e6db74">&#34;&lt;stdin&gt;&#34;</span>, line <span style="color:#ae81ff">1</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
    Should I go to bed soon<span style="color:#960050;background-color:#1e0010">?</span>
  File <span style="color:#e6db74">&#34;&lt;string&gt;&#34;</span>, line <span style="color:#ae81ff">1</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
    It<span style="color:#e6db74">&#39;s already the limit</span>
<span style="color:#a6e22e">ZeroDivisionError</span>: division by zero
</code></pre></div><p>I see, a divide by zero runtime error, which is as expected.
But,
&ldquo;Should I sleep now?&rdquo; &ldquo;It&rsquo;s already the limit.&rdquo;
What is this?</p>
<p>Python on this machine has not been modified, nor is the standard library.
No program is written to cause this phenomenon.
What are the possible causes?</p>
<h2 id="if-an-error-occurs-while-executing-the-source-file-the-corresponding-code-is-displayed">If an error occurs while executing the source file, the corresponding code is displayed</h2>
<p>Stay away from the machine giving the weird message and check the nature of the Traceback you see when the error occurs.
First, execute the source file <code>hello.py</code> that causes division by zero.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python:hello.py" data-lang="python:hello.py"><span style="color:#66d9ef">print</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">/</span><span style="color:#ae81ff">0</span>)
</code></pre></div><pre><code class="language-shell-session" data-lang="shell-session">$python3 hello.py
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">Traceback (most recent call last):
  File <span style="color:#e6db74">&#34;hello.py&#34;</span>, line <span style="color:#ae81ff">1</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
    <span style="color:#66d9ef">print</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">/</span><span style="color:#ae81ff">0</span>)
<span style="color:#a6e22e">ZeroDivisionError</span>: division by zero
</code></pre></div><p>Traceback shows that the error occurred on the line <code>print(1/0)</code>.
This is the expected behavior.</p>
<h2 id="the-code-at-the-error-point-is-obtained-after-the-error-occurred">The code at the error point is obtained after the error occurred</h2>
<p>As above, it is convenient for Traceback to display the source code that caused the error, but Python does not retain the source code during execution because it converts the source code to bytecode before executing it. must.
What&rsquo;s going on.
Actually, Python reads the source code again after getting a run-time error and gets the code at the relevant place.
To confirm this, I made <code>hello2.py</code> with a line added on top of <code>hello.py</code>.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python:hello2.py" data-lang="python:hello2.py">input(<span style="color:#e6db74">&#34;Please input&gt; &#34;</span>)
<span style="color:#66d9ef">print</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">/</span><span style="color:#ae81ff">0</span>)
</code></pre></div><p>Wait for input with <code>input</code> before division by zero.
During this time, I will rewrite the source code of <code>hello2.py</code> itself with an editor.
First of all, it starts execution and waits for input.</p>
<pre><code class="language-shell-session" data-lang="shell-session">$python3 hello2.py
Please input&gt;
</code></pre><p>Replace the second line with some text.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python:hello2.py" data-lang="python:hello2.py">input(<span style="color:#e6db74">&#34;Please input&gt; &#34;</span>)
Are you sleepy<span style="color:#960050;background-color:#1e0010">?</span>
</code></pre></div><p>Proper input is given to the process waiting for input, and the process proceeds.</p>
<pre><code class="language-shell-session" data-lang="shell-session">$python3 hello2.py
Please input&gt; 123[Enter]
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">Traceback (most recent call last):
  File <span style="color:#e6db74">&#34;hello2.py&#34;</span>, line <span style="color:#ae81ff">2</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
    Are you sleepy<span style="color:#960050;background-color:#1e0010">?</span>
<span style="color:#a6e22e">ZeroDivisionError</span>: division by zero
</code></pre></div><p>It is a division by zero error that should have occurred with the code <code>print(1/0)</code>, but the text after rewriting, &ldquo;Are you sleepy?&rdquo; was displayed in Traceback.
You can see that the source code is loaded after the error occurs.</p>
<h2 id="if-there-is-no-source-file-the-code-at-the-error-will-not-be-displayed">If there is no source file, the code at the error will not be displayed</h2>
<p>But what if you get an error on standard input or execution of a string?
The code is not stored in a file, so there is nothing to read after the error.
Let&rsquo;s give <code>hello.py</code> to Python as standard input.</p>
<pre><code class="language-shell-session" data-lang="shell-session">$ python3 &lt;hello.py
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">Traceback (most recent call last):
  File <span style="color:#e6db74">&#34;&lt;stdin&gt;&#34;</span>, line <span style="color:#ae81ff">1</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
<span style="color:#a6e22e">ZeroDivisionError</span>: division by zero
</code></pre></div><p>It is shown to be the first line of <code>&lt;stdin&gt;</code>, but the code at the actual error is not printed.
But what about giving the code as a command line argument?</p>
<pre><code class="language-shell-session" data-lang="shell-session">$python3 -c'print(1/0)'
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">Traceback (most recent call last):
  File <span style="color:#e6db74">&#34;&lt;string&gt;&#34;</span>, line <span style="color:#ae81ff">1</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
<span style="color:#a6e22e">ZeroDivisionError</span>: division by zero
</code></pre></div><p>Similarly, it is shown as the first line of <code>&lt;string&gt;</code>, but the code at the error point is not displayed.
The source code cannot be obtained because it is not a file that actually exists, whether it is <code>&lt;stdin&gt;</code> or <code>&lt;string&gt;</code>.</p>
<h2 id="what-are-stdin-and-string">What are <code>&lt;stdin&gt;</code> and <code>&lt;string&gt;</code></h2>
<p>In the above Traceback, <code>File &quot;&lt;stdin&gt;&quot;</code> and <code>File &quot;&lt;string&gt;&quot;</code> were displayed, but what is this?
<a href="https://docs.python.jp/3/library/functions.html?highlight=compile#compile">compile function documentation</a></p>
<blockquote>
<p>The filename argument must be the file from which the code is read; pass a recognizable value if it is not read from a file (<code>'&lt;string&gt;'</code> is commonly used. ).</p>
</blockquote>
<p>There is.
If there is no source file, the character string indicating the origin of the source code is set as the &ldquo;file name&rdquo;.
Python will rely on the &ldquo;filename&rdquo; specified here to create a Traceback when it encounters an error executing bytecode.
Since files such as <code>&lt;stdin&gt;</code> and <code>&lt;string&gt;</code> do not exist, the code indicating the error location cannot be obtained in these cases, and nothing is displayed there.</p>
<h2 id="what-if-there-is-a-file-that-shouldnt-exist">What if there is a file that shouldn&rsquo;t exist?</h2>
<p>But are there absolutely no files like <code>&lt;stdin&gt;</code> or <code>&lt;string&gt;</code>?
What would happen if there were?
These files are stored in a certain directory on a certain machine that was introduced at the beginning.</p>
<pre><code class="language-shell-session" data-lang="shell-session">$ls
&lt;stdin&gt; &lt;string&gt;
$ cat'&lt;stdin&gt;'
Should I go to bed soon?
$ cat'&lt;string&gt;'
It's already the limit
</code></pre><p>Input to Python&rsquo;s interactive mode is from standard input, so the &ldquo;filename&rdquo; set in the bytecode is <code>&lt;stdin&gt;</code>.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#f92672">&gt;&gt;&gt;</span> eval(<span style="color:#e6db74">&#34;1/0&#34;</span>)
</code></pre></div><p>In addition, the code calls the <code>eval</code> function, which compiles the string into bytecode.
The &ldquo;file name&rdquo; of the bytecode is <code>&lt;string&gt;</code>.
When an error occurs, Python trusts these &ldquo;filenames&rdquo; and creates a Traceback, so it prints the first line of each prepared file.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python">Traceback (most recent call last):
  File <span style="color:#e6db74">&#34;&lt;stdin&gt;&#34;</span>, line <span style="color:#ae81ff">1</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
    Should I go to bed soon<span style="color:#960050;background-color:#1e0010">?</span>
  File <span style="color:#e6db74">&#34;&lt;string&gt;&#34;</span>, line <span style="color:#ae81ff">1</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
    It<span style="color:#e6db74">&#39;s already the limit</span>
<span style="color:#a6e22e">ZeroDivisionError</span>: division by zero
</code></pre></div><p>This is the cause of the strange phenomenon.
At this time, the source file seems to be searched from <a href="https://docs.python.jp/3/library/sys.html#sys.path"><code>sys.path</code></a>, so <code>&lt;stdin&gt;</code> and <code>&lt; This happens if string&gt;</code> is in a directory contained in <code>sys.path</code>.</p>
<h2 id="reference">Reference</h2>
<p>Weird error message was <a href="https://twitter.com/brandon_rhodes/status/843998606113890305">introduced on Twitter</a>.
For bytecode, refer to <a href="https://docs.python.jp/3/library/dis.html">Document of <code>dis</code> module</a>.</p>

    </article>
  </div>

  
  
  
  <script>
  window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
  ga('create', 'UA-169005401-1', 'auto');
  ga('send', 'pageview');
  </script>
  <script async src='https://www.google-analytics.com/analytics.js'></script>
  

  

  
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#216942",
      "text": "#b2d192"
    },
    "button": {
      "background": "#afed71"
    }
  }
})});
</script>

</body>

</html>
