<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Zsh on Some Title</title>
    <link>https://japan2018.github.io/tags/zsh/</link>
    <description>Recent content in Zsh on Some Title</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Wed, 01 Jan 2020 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://japan2018.github.io/tags/zsh/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Using anaconda&#39;s virtual environment with Zsh (defect support)</title>
      <link>https://japan2018.github.io/using-anacondas-virtual-environment-with-zsh-defect-support-fbcb5/</link>
      <pubDate>Wed, 01 Jan 2020 00:00:00 +0000</pubDate>
      
      <guid>https://japan2018.github.io/using-anacondas-virtual-environment-with-zsh-defect-support-fbcb5/</guid>
      <description># Overview  Using Jupyter Notebook of anaconda installed with pyenv with zsh (defect support), following trial and error as a memorandum for using Jupyter Notebook with Zsh Keep.
Defect status  $ conda info -e can confirm the virtual environment, but cannot activate it with $ conda activate &amp;lt;virtual environment name&amp;gt;  #Environment Mac OS Mojave
Method 1. Try running the virtual environment $ conda activate &amp;lt;virtual environment name&amp;gt; Error message returned</description>
    </item>
    
  </channel>
</rss>